// Auto-generated by scripts/generate-legal-pages.mjs from
// FLOSMOSIS/legal/Terms-of-Service.docx.
// Re-run the generator after any source-document update.
//
// Effective 27 April 2026 · Version 1.0 · ACN 697 323 925.

import type { CSSProperties } from 'react';

export default function TermsPage() {
  return (
    <div style={styles.container}>
      <div style={styles.header}>
        <a href="/" style={styles.backButton}>← Back</a>
        <div style={styles.updatedText}>Last updated: 27 April 2026</div>
      </div>

      <div style={styles.content}>
        <h1 style={styles.mainTitle}>FLOSMOSIS.COM TERMS OF SERVICE</h1>

        <div style={styles.subtitle}>
          <p><strong>FLOSMOSIS PTY LTD</strong></p>
          <p><strong>ACN 697 323 925</strong> · <strong>ABN 80 697 323 925</strong></p>
          <p>Registered office: 55 Reginald Road, Googong NSW 2620</p>
        </div>

        <p><strong>Effective Date:</strong> 27 April 2026<br />
        <strong>Version:</strong> 1.0<br />
        <strong>Last Updated:</strong> 27 April 2026</p>

        <hr style={styles.divider} />


        <h2 style={styles.heading}>1. Introduction and Acceptance</h2>
        <p>These Terms of Service (&quot;Terms&quot;) govern your access to and use of the flosmosis.com website and the FLOSTRUCTION product and its related applications (the &quot;Services&quot;), operated by FLOSMOSIS PTY LTD (ACN 697 323 925; in these Terms, &quot;FLOSMOSIS,&quot; &quot;we,&quot; &quot;our,&quot; or &quot;us&quot;).</p>
        <p>By accessing or using the Services, you agree to be bound by these Terms. If you do not agree to these Terms, you must not use the Services.</p>
        <p>These Terms constitute a binding agreement between you and FLOSMOSIS. They are governed by the laws of the Australian Capital Territory, Australia.</p>
        <h2 style={styles.heading}>2. Separate Agreements</h2>
        <h3 style={styles.subheading}>2.1 Relationship to the WLES Foundation</h3>
        <p>The FLOSTRUCTION product is a reference implementation of the WLES v1.0 specification. The WLES specification itself, including its implementation by FLOSTRUCTION or by any other party, is governed by the irrevocable open-licence commitments of the WLES Foundation, published at foundation.wles.io/constitution.</p>
        <p>These Terms govern your commercial relationship with FLOSMOSIS as the operator of FLOSTRUCTION. They do not affect, and are not affected by, the open-licence status of the WLES standard itself. Any party may implement WLES without agreeing to these Terms.</p>
        <h3 style={styles.subheading}>2.2 Relationship to Customer Agreements</h3>
        <p>Where you are a business customer of FLOSMOSIS and have entered into a separate customer agreement (such as a Founding Customer Agreement, a Master Services Agreement, or a Partner Agreement), the terms of that customer agreement govern the commercial relationship and prevail over these Terms to the extent of any inconsistency. These Terms apply as base terms for website visitors, evaluators, and parties who have not entered into a separate customer agreement.</p>
        <h2 style={styles.heading}>3. Eligibility</h2>
        <p>To use the Services, you must be:</p>
        <ul style={styles.list}>
          <li>at least 18 years of age, and</li>
          <li>legally competent to enter into a binding agreement under Australian law, and</li>
          <li>acting in a capacity consistent with the intended use of the Services (as a worker, supervisor, employer administrator, partner integrator, or other legitimate user).</li>
        </ul>
        <p>If you are using the Services on behalf of a legal entity, you warrant that you have the authority to bind that entity to these Terms.</p>
        <h2 style={styles.heading}>4. Your Account</h2>
        <h3 style={styles.subheading}>4.1 Account registration</h3>
        <p>Access to most Services requires registration of an account. You agree to provide accurate, current, and complete information during registration and to keep your account information updated.</p>
        <h3 style={styles.subheading}>4.2 Account security</h3>
        <p>You are responsible for maintaining the security of your account credentials (including phone number, OTP codes, API keys). You must notify us immediately at security@flosmosis.com of any unauthorised access to your account.</p>
        <h3 style={styles.subheading}>4.3 Account responsibility</h3>
        <p>You are responsible for all activity conducted through your account, whether authorised by you or not, subject to the qualification that FLOSMOSIS takes reasonable security measures as described in our Privacy Policy.</p>
        <h2 style={styles.heading}>5. Permitted Use and Prohibitions</h2>
        <h3 style={styles.subheading}>5.1 Permitted use</h3>
        <p>You may use the Services for their intended purposes, including:</p>
        <ul style={styles.list}>
          <li>as a worker, recording your shifts and receiving verified shift receipts;</li>
          <li>as a supervisor, reviewing and approving shift records;</li>
          <li>as an employer administrator, managing your organisation&apos;s shift records and generating payroll exports;</li>
          <li>as a partner integrator, integrating with the FLOSTRUCTION API under an applicable Partner Agreement;</li>
          <li>as a visitor to the website, reading publicly available content and contacting us through provided channels.</li>
        </ul>
        <h3 style={styles.subheading}>5.2 Prohibitions</h3>
        <p>You must not:</p>
        <ul style={styles.list}>
          <li>use the Services for any unlawful purpose;</li>
          <li>use the Services to record shift events you did not actually perform or supervise, or to falsify labour records;</li>
          <li>attempt to gain unauthorised access to other users&apos; data, to our systems, or to any systems connected to the Services;</li>
          <li>interfere with or disrupt the operation of the Services;</li>
          <li>reverse-engineer, decompile, or disassemble the Services except to the extent such restriction is prohibited by law;</li>
          <li>use the Services to harass, abuse, or harm other users;</li>
          <li>impersonate another person or entity;</li>
          <li>use the Services to send spam or unsolicited commercial communications;</li>
          <li>scrape, data-mine, or otherwise extract bulk data from the Services except through our documented API under an applicable Partner Agreement;</li>
          <li>use the Services in a manner that would subject us to liability or that violates Australian or other applicable law.</li>
        </ul>
        <h2 style={styles.heading}>6. User Content and WLES Records</h2>
        <h3 style={styles.subheading}>6.1 User-submitted content</h3>
        <p>You are responsible for the accuracy of information you submit through the Services, including shift events, approval records, and organisational information.</p>
        <h3 style={styles.subheading}>6.2 The WLES integrity guarantee and its consequences</h3>
        <p>A defining feature of FLOSTRUCTION is that shift records are cryptographically sealed at the moment of creation using WLES v1.0. This means:</p>
        <ul style={styles.list}>
          <li>once a shift record is sealed, its content cannot be altered. Corrections are handled through new events appended to the chain.</li>
          <li>the integrity of the sealed record can be independently verified by any party holding the record.</li>
          <li>we cannot, even on the request of an employer or other party, retrospectively alter sealed records. We can only add corrective events to the chain.</li>
        </ul>
        <p>This is the feature that gives FLOSTRUCTION records their value. You acknowledge that by using the Services to record shift events, you are creating records with these integrity properties.</p>
        <h3 style={styles.subheading}>6.3 Licence to process user content</h3>
        <p>By submitting content to the Services, you grant FLOSMOSIS a non-exclusive, royalty-free licence to use, process, store, and display that content for the purposes of operating the Services. This licence is limited to the operational purposes set out in our Privacy Policy. It does not extend to unrelated commercial use.</p>
        <h2 style={styles.heading}>7. Fees and Billing</h2>
        <p>Where applicable, fees for the Services are set out in:</p>
        <ul style={styles.list}>
          <li>your customer agreement (for business customers); or</li>
          <li>the pricing page at flosmosis.com/pricing (for self-serve or default pricing).</li>
        </ul>
        <p>Unless otherwise agreed, fees are payable monthly in advance. GST is additional unless otherwise stated. Late payment may result in suspension of Services.</p>
        <h2 style={styles.heading}>8. Intellectual Property</h2>
        <h3 style={styles.subheading}>8.1 FLOSMOSIS intellectual property</h3>
        <p>The FLOSTRUCTION product, software, content on flosmosis.com, and related materials are the intellectual property of FLOSMOSIS, subject to the qualification that WLES itself is governed by the WLES Foundation&apos;s open licence and is not proprietary to FLOSMOSIS.</p>
        <h3 style={styles.subheading}>8.2 WLES specification</h3>
        <p>The WLES specification is available at wles.io under the Foundation&apos;s open licence. You may implement WLES without agreeing to these Terms and without any licence from FLOSMOSIS.</p>
        <h3 style={styles.subheading}>8.3 Your intellectual property</h3>
        <p>These Terms do not transfer any ownership of your intellectual property to FLOSMOSIS. Your data and content remain your property, subject to the operational licence granted under clause 6.3.</p>
        <h2 style={styles.heading}>9. Disclaimers</h2>
        <h3 style={styles.subheading}>9.1 Service provided as-is</h3>
        <p>Subject to our obligations under Australian Consumer Law, the Services are provided on an &quot;as is&quot; and &quot;as available&quot; basis. We do not warrant that the Services will be uninterrupted, error-free, or suited to any particular purpose beyond those expressly stated in our product documentation.</p>
        <h3 style={styles.subheading}>9.2 WLES integrity property</h3>
        <p>The cryptographic integrity guarantee of WLES applies to records after sealing. WLES does not guarantee the truth of the content asserted in a record at the moment of sealing. A user who records a false shift event creates a cryptographically valid but substantively untrue record. FLOSMOSIS is not responsible for the truth of user-submitted content.</p>
        <h3 style={styles.subheading}>9.3 Australian Consumer Law</h3>
        <p>To the extent that consumer guarantees under the Australian Consumer Law apply to our Services and cannot be excluded, our liability for failure to comply with a consumer guarantee is limited to (at our discretion) resupplying the Services or paying the cost of having the Services resupplied.</p>
        <h2 style={styles.heading}>10. Limitation of Liability</h2>
        <p>To the maximum extent permitted by Australian law, FLOSMOSIS&apos;s aggregate liability to you arising out of or in connection with these Terms is limited to the fees paid by you to FLOSMOSIS in the twelve months preceding the event giving rise to the claim, or A$500, whichever is greater.</p>
        <p>FLOSMOSIS is not liable for indirect, consequential, or special damages, including loss of profits, loss of business opportunity, loss of data (beyond specific data remediation obligations under applicable law), or damages arising from third-party claims, except to the extent such limitation is prohibited by law.</p>
        <p>This clause does not exclude or limit liability that cannot be excluded or limited under Australian law, including liability under the Australian Consumer Law.</p>
        <h2 style={styles.heading}>11. Termination</h2>
        <h3 style={styles.subheading}>11.1 Termination by you</h3>
        <p>You may terminate your use of the Services at any time by ceasing to access them. If you have a customer agreement with FLOSMOSIS, the termination terms of that agreement govern.</p>
        <h3 style={styles.subheading}>11.2 Termination by us</h3>
        <p>We may suspend or terminate your access to the Services:</p>
        <ul style={styles.list}>
          <li>for material breach of these Terms or any applicable customer agreement;</li>
          <li>for suspected fraudulent, illegal, or abusive use of the Services;</li>
          <li>if required to do so by law or regulatory order.</li>
        </ul>
        <p>Where practicable, we provide reasonable notice before termination.</p>
        <h3 style={styles.subheading}>11.3 Effect of termination</h3>
        <p>On termination:</p>
        <ul style={styles.list}>
          <li>your right to access the Services ends;</li>
          <li>WLES records you created during your use of the Services remain part of the relevant WLES chains (they are not deleted — deletion of WLES records would undermine their integrity property);</li>
          <li>your data handling rights under our Privacy Policy continue to apply, including rights of access, correction, and deletion of identity mapping information.</li>
        </ul>
        <h2 style={styles.heading}>12. Changes to These Terms</h2>
        <p>We may update these Terms from time to time. The current version is always published at flosmosis.com/terms. Material changes are notified to registered users by email at least thirty days before the changes take effect. Continued use of the Services after changes take effect constitutes acceptance of the updated Terms.</p>
        <h2 style={styles.heading}>13. Governing Law and Dispute Resolution</h2>
        <h3 style={styles.subheading}>13.1 Governing law</h3>
        <p>These Terms are governed by the laws of the Australian Capital Territory, Australia.</p>
        <h3 style={styles.subheading}>13.2 Jurisdiction</h3>
        <p>You agree to submit to the non-exclusive jurisdiction of the courts of the Australian Capital Territory for any dispute arising out of or in connection with these Terms.</p>
        <h3 style={styles.subheading}>13.3 Good-faith negotiation</h3>
        <p>Before commencing legal proceedings, the parties agree to attempt in good faith to resolve any dispute through direct negotiation for a period of at least thirty days.</p>
        <h2 style={styles.heading}>14. Miscellaneous</h2>
        <h3 style={styles.subheading}>14.1 Severability</h3>
        <p>If any provision of these Terms is held invalid or unenforceable, the remaining provisions continue in full force and effect.</p>
        <h3 style={styles.subheading}>14.2 No waiver</h3>
        <p>Failure by either party to enforce any provision of these Terms does not constitute a waiver of that provision or any other provision.</p>
        <h3 style={styles.subheading}>14.3 Assignment</h3>
        <p>You may not assign or transfer your rights or obligations under these Terms without our prior written consent. We may assign these Terms in connection with a merger, acquisition, or sale of assets, subject to the acquiring party&apos;s agreement to honour these Terms.</p>
        <h3 style={styles.subheading}>14.4 Entire agreement</h3>
        <p>These Terms, together with our Privacy Policy and any applicable customer agreement, constitute the entire agreement between you and FLOSMOSIS regarding the Services. They supersede all prior agreements and understandings.</p>
        <h3 style={styles.subheading}>14.5 Notices</h3>
        <p>Notices to FLOSMOSIS should be sent to legal@flosmosis.com. Notices to you will be sent to the email address associated with your account or posted on the website.</p>
        <h2 style={styles.heading}>15. Contact</h2>
        <p>For questions about these Terms:</p>
        <p>FLOSMOSIS PTY LTD Email: legal@flosmosis.com Post: 55 Reginald Road, Googong NSW 2620</p>



      </div>
    </div>
  );
}

const styles: { [key: string]: CSSProperties } = {
  container: {
    backgroundColor: '#0a0a1a',
    color: 'rgba(255, 255, 255, 0.85)',
    minHeight: '100vh',
    padding: '20px',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
    lineHeight: '1.6',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '40px',
    maxWidth: '800px',
    margin: '0 auto 40px',
  },
  backButton: {
    color: '#888',
    textDecoration: 'none',
    fontSize: '16px',
    transition: 'color 0.2s',
  },
  updatedText: {
    fontSize: '12px',
    color: '#666',
  },
  content: {
    maxWidth: '800px',
    margin: '0 auto',
  },
  mainTitle: {
    fontSize: '32px',
    color: 'white',
    marginBottom: '20px',
    marginTop: '0',
  },
  subtitle: {
    marginBottom: '20px',
  },
  heading: {
    fontSize: '18px',
    color: 'white',
    marginTop: '30px',
    marginBottom: '15px',
    fontWeight: 'bold',
  },
  subheading: {
    fontSize: '16px',
    color: 'rgba(255, 255, 255, 0.9)',
    marginTop: '20px',
    marginBottom: '10px',
    fontWeight: '600',
  },
  divider: {
    borderColor: 'rgba(255, 255, 255, 0.1)',
    margin: '30px 0',
  },
  list: {
    marginLeft: '20px',
    marginBottom: '15px',
  },
};
