// Auto-generated by scripts/generate-legal-pages.mjs from
// FLOSMOSIS/legal/Privacy-Policy.docx.
// Re-run the generator after any source-document update.
//
// Effective 27 April 2026 · Version 1.0 · ACN 697 323 925.

import type { CSSProperties } from 'react';

export default function PrivacyPage() {
  return (
    <div style={styles.container}>
      <div style={styles.header}>
        <a href="/" style={styles.backButton}>← Back</a>
        <div style={styles.updatedText}>Last updated: 27 April 2026</div>
      </div>

      <div style={styles.content}>
        <h1 style={styles.mainTitle}>FLOSMOSIS.COM PRIVACY POLICY</h1>

        <div style={styles.subtitle}>
          <p><strong>FLOSMOSIS PTY LTD</strong></p>
          <p><strong>ACN 697 323 925</strong> · <strong>ABN 80 697 323 925</strong></p>
          <p>Registered office: 55 Reginald Road, Googong NSW 2620</p>
        </div>

        <p><strong>Effective Date:</strong> 27 April 2026<br />
        <strong>Version:</strong> 1.0<br />
        <strong>Last Updated:</strong> 27 April 2026</p>

        <hr style={styles.divider} />


        <h2 style={styles.heading}>1. Introduction</h2>
        <p>This Privacy Policy describes how FLOSMOSIS PTY LTD (ACN 697 323 925; in this document, &quot;FLOSMOSIS,&quot; &quot;we,&quot; &quot;our,&quot; or &quot;us&quot;) handles personal information in connection with:</p>
        <ul style={styles.list}>
          <li>the flosmosis.com website;</li>
          <li>the FLOSTRUCTION product and its related applications (the FLOSTRUCTION PWA available at flosmosis.com/field and the FLOSTRUCTION admin applications);</li>
          <li>the FLOSTRUCTION API at api.flosmosis.com; and</li>
          <li>the administrative support FLOSMOSIS provides to the WLES Foundation as its Founding Member.</li>
        </ul>
        <p>This Policy applies in addition to, and operates alongside, any WLES Foundation privacy practices published at foundation.wles.io/privacy. The Foundation&apos;s privacy practices govern Foundation-level data (such as Member correspondence and Foundation governance records). This Policy governs FLOSMOSIS-level data (including data arising from use of the FLOSTRUCTION product).</p>
        <p>FLOSMOSIS is an Australian Privacy Principles entity within the meaning of the Privacy Act 1988 (Commonwealth). We comply with the Australian Privacy Principles and with the Australian Privacy Act in our handling of personal information.</p>
        <h2 style={styles.heading}>2. Personal Information We Collect</h2>
        <p>FLOSMOSIS collects personal information in the following categories and for the following purposes.</p>
        <h3 style={styles.subheading}>2.1 Information collected from users of the flosmosis.com website</h3>
        <ul style={styles.list}>
          <li>Contact information provided voluntarily (name, email address, phone number, company name) when you contact us, subscribe to updates, or apply for the Founding Customer Programme;</li>
          <li>Technical information automatically collected when you access the site (IP address, browser type, device identifiers, approximate location derived from IP, pages viewed, time spent on pages);</li>
          <li>Communications you send to us (email correspondence, support requests, form submissions).</li>
        </ul>
        <h3 style={styles.subheading}>2.2 Information collected in connection with the FLOSTRUCTION product</h3>
        <p>FLOSTRUCTION operates under a dual-party data model: the employer (FLOSTRUCTION&apos;s direct customer) contracts for the service, and workers of the employer use the worker-facing PWA. Information is collected from both parties.</p>
        <p>From employers and their administrators:</p>
        <ul style={styles.list}>
          <li>business contact information (name, role, email, phone, business ABN);</li>
          <li>billing information (payment method details, which are processed by our payment processor and not retained by us);</li>
          <li>organisational information (company name, registered address, labour hire licence numbers where applicable).</li>
        </ul>
        <p>From workers using the FLOSTRUCTION PWA:</p>
        <ul style={styles.list}>
          <li>identity information (first name, last name, mobile phone number for OTP authentication);</li>
          <li>employment context (engaging employer identifier, assigned sites, supervisor relationships);</li>
          <li>shift events (clock-in times, clock-out times, break periods, hours worked, approval records);</li>
          <li>location information captured at shift events (geolocation data, with accuracy radius, collected for the specific purpose of verifying site attendance);</li>
          <li>device and session information (device type, app version, session timestamps, approximate IP-derived location).</li>
        </ul>
        <p>From supervisors:</p>
        <ul style={styles.list}>
          <li>identity information (name, role, mobile phone number for SMS approvals);</li>
          <li>approval records (which shifts were approved, approval timestamps, approval methods).</li>
        </ul>
        <h3 style={styles.subheading}>2.3 Information about your interactions with the WLES Foundation</h3>
        <p>In our capacity as Founding Member of the WLES Foundation, we may collect:</p>
        <ul style={styles.list}>
          <li>correspondence sent to foundation@wles.io or standards@wles.io;</li>
          <li>information provided in connection with proposed amendments to the WLES specification;</li>
          <li>information provided in connection with Member applications.</li>
        </ul>
        <p>Such information is held by FLOSMOSIS on the Foundation&apos;s behalf and is transferred to the Foundation on its separate incorporation (see the Foundation Constitution at foundation.wles.io/constitution).</p>
        <h2 style={styles.heading}>3. How We Use Personal Information</h2>
        <p>We use personal information only for the following purposes.</p>
        <p>Operating the FLOSTRUCTION product: processing shift events, generating WLES receipts, delivering receipts to workers and employers, producing payroll export files, providing customer administration tools.</p>
        <p>Authenticating users: verifying identity for access to the worker PWA, the supervisor SMS approval flow, and the employer admin dashboard.</p>
        <p>Supporting customers: responding to enquiries, providing technical support, investigating issues raised by users, onboarding new customers.</p>
        <p>Improving the product: analysing usage patterns, identifying bugs and performance issues, developing new features. This analysis is performed on aggregated or de-identified data wherever feasible.</p>
        <p>Complying with legal obligations: meeting our record-keeping obligations under Australian law, responding to lawful requests from regulators, courts, and tribunals.</p>
        <p>Communications: sending transactional messages (shift approvals, receipt delivery, billing notices) and, with your express consent, product updates and marketing communications.</p>
        <p>Standards development: in our capacity as Founding Member of the WLES Foundation, supporting the development of the WLES specification and related standards artefacts. Information collected in this context is handled in accordance with the Foundation&apos;s separate privacy practices.</p>
        <p>We do not use personal information for purposes unrelated to these functions. We do not sell personal information to third parties.</p>
        <h2 style={styles.heading}>4. The Cryptographic Nature of WLES Records</h2>
        <p>A distinctive feature of FLOSTRUCTION is that shift records are cryptographically sealed using the WLES v1.0 standard. This has specific consequences for personal information handling that users should understand.</p>
        <p>Once a WLES event is sealed, its content cannot be altered without the alteration being detectable. This integrity property is the feature that gives WLES records their evidentiary value. It also means that corrections to shift records are handled through new events appended to the chain (rather than through modification of the original event).</p>
        <p>For personal information handling, this architectural choice has the following implications:</p>
        <p>Identity binding is separable from the cryptographic chain. Identities of workers, supervisors, and employers are represented in WLES events by opaque identifiers (UUIDs), not by names or direct personal identifiers. The mapping from identifier to real-world identity is stored separately from the chain. This design permits compliant response to deletion requests: the identity-to-identifier mapping can be deleted, rendering historical chain records no longer linkable to the individual, while preserving chain integrity for remaining subjects.</p>
        <p>Deletion requests are honoured at the identity mapping layer. Where an individual exercises rights under the Privacy Act to request deletion of their personal information, we delete the identity mapping for that individual from the operational systems within reasonable timeframes, subject to the exceptions described in Section 8.</p>
        <p>Historical shift data is retained. Historical WLES records (containing opaque identifiers, shift times, site identifiers, and verified event hashes) are retained for the periods described in Section 8, reflecting our obligations under Australian employment, tax, and evidence law. After identity mapping deletion, such records cannot be linked to the individual.</p>
        <h2 style={styles.heading}>5. Disclosure of Personal Information</h2>
        <p>We disclose personal information only in the following circumstances.</p>
        <p>To the employer who engages FLOSTRUCTION services in relation to their workers: the employer receives shift data, approval records, and worker identity information for the workers engaged through their organisation. This is inherent in the nature of the service.</p>
        <p>To the worker in relation to their own data: workers receive their own shift records, receipt URLs, and verification data. Workers may share their own WLES receipts with third parties (such as unions, legal advisers, or tribunals) at their own discretion.</p>
        <p>To payroll platforms and related counterparties integrated at the employer&apos;s direction: where an employer has authorised integration between FLOSTRUCTION and a third-party payroll platform, accounting system, or similar service, we share shift data with that service in accordance with the employer&apos;s authorisation.</p>
        <p>To our service providers: we engage third-party service providers (hosting, payment processing, SMS delivery, email delivery, error monitoring) who process personal information on our behalf. These providers are bound by contractual obligations to handle personal information only for our purposes and in accordance with applicable privacy law.</p>
        <p>To regulators, courts, and tribunals: where we are required by law to disclose personal information, or where we in good faith believe disclosure is necessary to protect our rights, to comply with a legal obligation, or to respond to a valid government request.</p>
        <p>In connection with business transactions: if we are involved in a merger, acquisition, or sale of assets, personal information may be transferred as part of that transaction, subject to the acquiring entity&apos;s commitment to respect the privacy obligations set out in this Policy.</p>
        <p>We do not disclose personal information for commercial purposes unrelated to the services we provide.</p>
        <h2 style={styles.heading}>6. Cross-Border Disclosure</h2>
        <p>We primarily store personal information within Australia. Some service providers we engage (for example, cloud infrastructure providers, email delivery providers, error monitoring services) may store, process, or have access to personal information outside Australia.</p>
        <p>Where personal information is disclosed to an overseas recipient, we take reasonable steps to ensure that the recipient does not breach the Australian Privacy Principles in relation to the information. We enter into contractual arrangements with overseas service providers requiring them to comply with privacy obligations substantially similar to those under Australian law.</p>
        <p>Specific overseas jurisdictions in which personal information may be processed include the United States (cloud infrastructure, payment processing, email delivery) and the European Union (certain infrastructure services). Users who wish to understand the specific jurisdictional processing arrangements for particular service providers may contact us at privacy@flosmosis.com.</p>
        <h2 style={styles.heading}>7. Security</h2>
        <p>We take reasonable steps to protect personal information from misuse, interference, loss, and from unauthorised access, modification, or disclosure. Our security measures include:</p>
        <ul style={styles.list}>
          <li>encryption of personal information in transit (TLS 1.2 or higher) and at rest (database-level encryption);</li>
          <li>cryptographic sealing of shift event records via WLES v1.0, which provides tamper-evident integrity beyond standard database integrity;</li>
          <li>authentication controls on all administrative access, including multi-factor authentication for administrator accounts;</li>
          <li>role-based access controls limiting employee and contractor access to personal information on a need-to-know basis;</li>
          <li>audit logging of administrative actions;</li>
          <li>regular security reviews and penetration testing conducted at periodic intervals.</li>
        </ul>
        <p>Despite these measures, no method of electronic storage or transmission is perfectly secure. Users should understand that any disclosure of personal information to FLOSMOSIS carries residual risk.</p>
        <h2 style={styles.heading}>8. Retention of Personal Information</h2>
        <p>We retain personal information for the following periods.</p>
        <p>Worker shift records and WLES chain data: retained for a minimum of seven years from the date of each shift, consistent with the record-keeping obligations under section 535 of the Fair Work Act 2009 (Commonwealth) and associated regulations. For workers whose shifts occurred under employers subject to state labour hire licensing regimes, retention periods may be longer where state legislation requires.</p>
        <p>Identity mapping (linking WLES opaque identifiers to named individuals): retained for the same period as the underlying shift records, subject to deletion requests under the Privacy Act. When a deletion request is honoured, the identity mapping is removed but the underlying chain records remain (with their opaque identifiers, no longer linkable to the individual).</p>
        <p>Customer billing and account information: retained for at least seven years after the end of the customer relationship, consistent with tax and business record-keeping obligations.</p>
        <p>Communications with users: retained for up to seven years after the communication, or longer where retention is required by law.</p>
        <p>Technical logs: retained for up to twelve months, used for security monitoring and incident investigation.</p>
        <p>Foundation-related correspondence: retained by FLOSMOSIS until the Foundation&apos;s separate incorporation, at which point it is transferred to the Foundation.</p>
        <p>After the applicable retention period, personal information is either deleted or irreversibly anonymised.</p>
        <h2 style={styles.heading}>9. Your Rights</h2>
        <p>Under the Australian Privacy Principles, you have the following rights in relation to your personal information held by FLOSMOSIS:</p>
        <p>Right of access: you may request access to the personal information we hold about you.</p>
        <p>Right of correction: you may request that we correct personal information that is inaccurate, incomplete, or out-of-date.</p>
        <p>Right of deletion: you may request that we delete personal information we hold about you, subject to exceptions where retention is required by law or by our legitimate business interests (such as outstanding obligations under existing customer agreements).</p>
        <p>Right to withdraw consent: where we process personal information on the basis of your consent, you may withdraw that consent at any time. Withdrawal of consent does not affect the lawfulness of processing conducted before withdrawal.</p>
        <p>Right to complain: you may complain to us about our handling of your personal information by contacting privacy@flosmosis.com. If you are dissatisfied with our response, you may complain to the Office of the Australian Information Commissioner at oaic.gov.au.</p>
        <p>To exercise any of these rights, contact privacy@flosmosis.com. We will respond within thirty days.</p>
        <h2 style={styles.heading}>10. Children&apos;s Personal Information</h2>
        <p>FLOSTRUCTION is designed for use by workers over the age of 18. We do not knowingly collect personal information from children under 18. If you believe we have inadvertently collected such information, contact privacy@flosmosis.com and we will take reasonable steps to delete it.</p>
        <p>Where a worker over 18 operates under a specific labour arrangement involving young workers (for example, in some agricultural or apprenticeship contexts), FLOSMOSIS does not separately process information about those young workers unless they are themselves registered users of the FLOSTRUCTION system with appropriate consents.</p>
        <h2 style={styles.heading}>11. Cookies and Similar Technologies</h2>
        <p>The flosmosis.com website uses cookies and similar technologies for the following purposes:</p>
        <ul style={styles.list}>
          <li>Essential cookies: required for the operation of the website and the FLOSTRUCTION applications (session management, authentication, security). These cookies cannot be disabled.</li>
          <li>Analytics cookies: used to understand how visitors interact with the site, so that we can improve functionality. Analytics data is aggregated and does not identify individuals.</li>
          <li>Functional cookies: used to remember user preferences such as language and display settings.</li>
        </ul>
        <p>We do not use cookies for third-party advertising or for tracking users across non-FLOSMOSIS websites.</p>
        <p>Users may disable non-essential cookies through their browser settings. Disabling essential cookies will impair the operation of the FLOSTRUCTION applications.</p>
        <h2 style={styles.heading}>12. Changes to This Policy</h2>
        <p>We may update this Policy from time to time. The current version is always published at flosmosis.com/privacy. Material changes are notified to existing users by email at least thirty days before the changes take effect. The date at the top of this Policy indicates when it was last updated.</p>
        <h2 style={styles.heading}>13. Contact</h2>
        <p>For privacy enquiries:</p>
        <p>FLOSMOSIS PTY LTD Privacy Officer: Lauren Kate de Mestre, Corporate Counsel Email: privacy@flosmosis.com Post: 55 Reginald Road, Googong NSW 2620</p>
        <p>For Foundation-related privacy matters: Email: foundation@wles.io</p>



      </div>
    </div>
  );
}

const styles: { [key: string]: CSSProperties } = {
  container: {
    backgroundColor: '#0a0a1a',
    color: 'rgba(255, 255, 255, 0.85)',
    minHeight: '100vh',
    padding: '20px',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
    lineHeight: '1.6',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '40px',
    maxWidth: '800px',
    margin: '0 auto 40px',
  },
  backButton: {
    color: '#888',
    textDecoration: 'none',
    fontSize: '16px',
    transition: 'color 0.2s',
  },
  updatedText: {
    fontSize: '12px',
    color: '#666',
  },
  content: {
    maxWidth: '800px',
    margin: '0 auto',
  },
  mainTitle: {
    fontSize: '32px',
    color: 'white',
    marginBottom: '20px',
    marginTop: '0',
  },
  subtitle: {
    marginBottom: '20px',
  },
  heading: {
    fontSize: '18px',
    color: 'white',
    marginTop: '30px',
    marginBottom: '15px',
    fontWeight: 'bold',
  },
  subheading: {
    fontSize: '16px',
    color: 'rgba(255, 255, 255, 0.9)',
    marginTop: '20px',
    marginBottom: '10px',
    fontWeight: '600',
  },
  divider: {
    borderColor: 'rgba(255, 255, 255, 0.1)',
    margin: '30px 0',
  },
  list: {
    marginLeft: '20px',
    marginBottom: '15px',
  },
};
